

class TestError(Exception):
	pass

class InvalidError(TestError):
	pass